export enum EndPointsReports {
  MAIN_HOST = "https://erp.bnoop.net/api/",
  PurchaseAnalysisReport = "PurchaseReport/PurchaseAnalysisReport",
  PurchaseTotalReport = "PurchaseReport/PurchaseTotalReport",
  PurchaseReturnAnalysisReport = "PurchaseReturnReport/PurchaseReturnAnalysisReport",
  PurchaseReturnTotalReport = "PurchaseReturnReport/PurchaseReturnTotalReport",
  SalesAnalysisReport = "SalesReport/SalesAnalysisReport",
  SalesTotalReport = "SalesReport/SalesTotalReport",
  SalesReturnAnalysisReport = "SalesReturnReport/SalesReturnAnalysisReport",
  SalesReturnTotalReport = "SalesReturnReport/SalesReturnTotalReport",
  VendorAccountTotalReport = "VendorReport/VendorAccountTotalReport",
  VendorAccountAnalysisReport = "VendorReport/VendorAccountAnalysisReport",
  VendorTransactionsReport = "VendorReport/VendorTransactionsReport",
  VendorTotalBalancesReport = "VendorReport/VendorTotalBalancesReport",
  CustomerAccountTotalReport = "CustomerReport/CustomerAccountTotalReport",
  CustomerAccountAnalysisReport = "CustomerReport/CustomerAccountAnalysisReport",
  CustomerTransactionsReport = "CustomerReport/CustomerTransactionsReport",
  CustomerTotalBalancesReport = "CustomerReport/CustomerTotalBalancesReport",
}
